# Generated by Django 5.2.5 on 2025-08-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lordland', 'Lordland'), ('tenant', 'Tenant')], default='tenant', max_length=20),
        ),
    ]
